-- Reportes de pantallas dañadas en casitas
-- Auth de app: tabla privada Usuarios (no Supabase Auth)

CREATE TABLE IF NOT EXISTS public.reporte_pantallas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_usuario text NOT NULL,
  fecha_hora timestamp without time zone NOT NULL,
  numero_casita integer NOT NULL,
  fotos jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT reporte_pantallas_numero_casita_check CHECK (numero_casita BETWEEN 1 AND 50),
  CONSTRAINT reporte_pantallas_fotos_max_check CHECK (jsonb_array_length(fotos) <= 3)
);

COMMENT ON TABLE public.reporte_pantallas IS 'Reportes de pantallas dañadas en casitas';
COMMENT ON COLUMN public.reporte_pantallas.nombre_usuario IS 'Usuario de la sesión (tabla Usuarios)';
COMMENT ON COLUMN public.reporte_pantallas.fecha_hora IS 'Fecha y hora en zona America/Costa_Rica';
COMMENT ON COLUMN public.reporte_pantallas.numero_casita IS 'Número de casita entre 1 y 50';
COMMENT ON COLUMN public.reporte_pantallas.fotos IS 'Arreglo JSON [{url, ubicacion}] con ubicacion: Living | Cuarto Queen | Cuarto King';

ALTER TABLE public.reporte_pantallas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS reporte_pantallas_select ON public.reporte_pantallas;
DROP POLICY IF EXISTS reporte_pantallas_insert ON public.reporte_pantallas;
DROP POLICY IF EXISTS reporte_pantallas_update ON public.reporte_pantallas;
DROP POLICY IF EXISTS reporte_pantallas_delete ON public.reporte_pantallas;

-- Políticas abiertas para anon/authenticated porque la app usa sesión propia (Usuarios), no auth.uid()
CREATE POLICY reporte_pantallas_select
  ON public.reporte_pantallas
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY reporte_pantallas_insert
  ON public.reporte_pantallas
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY reporte_pantallas_update
  ON public.reporte_pantallas
  FOR UPDATE
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY reporte_pantallas_delete
  ON public.reporte_pantallas
  FOR DELETE
  TO anon, authenticated
  USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.reporte_pantallas TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
